# Generated by Django 5.1.7 on 2025-04-05 21:49

import apps.properties.models
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Property",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("last_updated", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=255)),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "property_type",
                    models.CharField(
                        choices=[
                            ("house", "House"),
                            ("apartment", "Apartment"),
                            ("land", "Land"),
                            ("duplex", "Duplex"),
                            ("commercial", "Commercial"),
                            ("villa", "Villa"),
                            ("townhouse", "Townhouse"),
                            ("bungalow", "Bungalow"),
                            ("mansion", "Mansion"),
                            ("penthouse", "Penthouse"),
                            ("studio", "Studio Apartment"),
                            ("flat", "Flat"),
                            ("office_space", "Office Space"),
                            ("warehouse", "Warehouse"),
                            ("factory", "Factory"),
                            ("plot", "Plot"),
                            ("shop", "Shop"),
                            ("retail", "Retail Space"),
                            ("hotel", "Hotel"),
                            ("restaurant", "Restaurant"),
                            ("farm", "Farm Land"),
                            ("resort", "Resort"),
                            ("mixed_use", "Mixed-Use Property"),
                            ("multi_family", "Multi-family Building"),
                            ("hostel", "Hostel"),
                            ("luxury", "Luxury Property"),
                            ("serviced_apartment", "Serviced Apartment"),
                            ("beach_house", "Beach House"),
                            ("cottage", "Cottage"),
                            ("vacation_home", "Vacation Home"),
                            ("co_working_space", "Co-working Space"),
                        ],
                        max_length=50,
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        max_digits=9,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(-90.0),
                            django.core.validators.MaxValueValidator(90.0),
                        ],
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        max_digits=9,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(-180.0),
                            django.core.validators.MaxValueValidator(180.0),
                        ],
                    ),
                ),
                ("bedrooms", models.IntegerField(blank=True, null=True)),
                ("bathrooms", models.IntegerField(blank=True, null=True)),
                ("square_feet", models.IntegerField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("available", "Available"),
                            ("sold", "Sold"),
                            ("under_negotiation", "Under Negotiation"),
                        ],
                        default="available",
                        max_length=50,
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="property_images/"
                    ),
                ),
                (
                    "video",
                    models.FileField(
                        blank=True, null=True, upload_to="property_videos/"
                    ),
                ),
                ("for_sale", models.BooleanField(default=False)),
                ("for_rent", models.BooleanField(default=False)),
                (
                    "assigned_agent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_properties",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Document",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("last_updated", models.DateTimeField(auto_now=True)),
                (
                    "document_type",
                    models.CharField(
                        choices=[
                            ("c_of_o", "Certificate of Occupancy"),
                            ("title_deed", "Title Deed"),
                            ("warranty_deed", "Warranty Deed"),
                            ("grant_deed", "Grant Deed"),
                            ("FAQ", "FAQ"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=apps.properties.models.upload_property_documents,
                    ),
                ),
                (
                    "property",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="properties.property",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
