DOCUMENT_TYPE_CHOICES = [
        ('c_of_o', 'Certificate of Occupancy'),
        ('title_deed', 'Title Deed'),
        ('warranty_deed', 'Warranty Deed'),
        ('grant_deed', 'Grant Deed'),
    ]


PROPERTY_STATUS_CHOICES = [
        ('available', 'Available'),
        ('sold', 'Sold'),
        ('under_negotiation', 'Under Negotiation'),
    ]
PROPERTY_TYPES = [
    ('house', 'House'),
    ('apartment', 'Apartment'),
    ('land', 'Land'),
    ('duplex', 'Duplex'),
    ('commercial', 'Commercial'),
    ('villa', 'Villa'),
    ('townhouse', 'Townhouse'),
    ('bungalow', 'Bungalow'),
    ('mansion', 'Mansion'),
    ('penthouse', 'Penthouse'),
    ('studio', 'Studio Apartment'),
    ('flat', 'Flat'),
    ('office_space', 'Office Space'),
    ('warehouse', 'Warehouse'),
    ('factory', 'Factory'),
    ('plot', 'Plot'),
    ('shop', 'Shop'),
    ('retail', 'Retail Space'),
    ('hotel', 'Hotel'),
    ('restaurant', 'Restaurant'),
    ('farm', 'Farm Land'),
    ('resort', 'Resort'),
    ('mixed_use', 'Mixed-Use Property'),
    ('multi_family', 'Multi-family Building'),
    ('hostel', 'Hostel'),
    ('luxury', 'Luxury Property'),
    ('serviced_apartment', 'Serviced Apartment'),
    ('beach_house', 'Beach House'),
    ('cottage', 'Cottage'),
    ('vacation_home', 'Vacation Home'),
    ('co_working_space', 'Co-working Space'),
]
